### ISSUE TITLE
Tourchmetrics error?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [danier97/LDMVFI#10]
I've successfully installed all dependencies through conda but I get this error when trying to interpolated a video.  Any ideas what's wrong here?

"C:\Users\importon\Documents\LDMVFI-main>python evaluate.py \--config configs/ldm/ldmvfi-vqflow-f32-c256-concat_max.yaml \--ckpt model/ldmvfi-vqflow-f32-c256-concat_max.ckpt \--dataset input/input.yuv \--out_dir output/ \--use_ddim
Traceback (most recent call last):
  File "C:\Users\importon\Documents\LDMVFI-main\evaluate.py", line 6, in <module>
    from main import instantiate_from_config
  File "C:\Users\importon\Documents\LDMVFI-main\main.py", line 6, in <module>
    import pytorch_lightning as pl
  File "C:\Users\importon\anaconda3\envs\ldmvfi\lib\site-packages\pytorch_lightning\__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\importon\anaconda3\envs\ldmvfi\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 25, in <module>
    from pytorch_lightning.callbacks.progress import ProgressBarBase, RichProgressBar, TQDMProgressBar
  File "C:\Users\importon\anaconda3\envs\ldmvfi\lib\site-packages\pytorch_lightning\callbacks\progress\__init__.py", line 22, in <module>
    from pytorch_lightning.callbacks.progress.rich_progress import RichProgressBar  # noqa: F401
  File "C:\Users\importon\anaconda3\envs\ldmvfi\lib\site-packages\pytorch_lightning\callbacks\progress\rich_progress.py", line 20, in <module>
    from torchmetrics.utilities.imports import _compare_version
ImportError: cannot import name '_compare_version' from 'torchmetrics.utilities.imports' (C:\Users\importon\anaconda3\envs\ldmvfi\lib\site-packages\torchmetrics\utilities\imports.py)"

**Comment by danier97** [comment]
Hi,

Sorry I don't have a clear idea what's causing this. Could you please share the output of `conda list`?

**Comment by laowang404** [comment]
Hi,
The same issue happens to me, I solve this issue by changing the src code of pytorch-lighting
`from torchmetrics.utilities.imports import compare_version` and `_RICH_AVAILABLE: bool = _package_available("rich") and compare_version("rich", operator.ge, "10.2.2")`
You can refer to the similar issue as well.
https://github.com/Lightning-AI/torchmetrics/issues/1923

**Comment by danier97** [comment]
> Hi, The same issue happens to me, I solve this issue by changing the src code of pytorch-lighting `from torchmetrics.utilities.imports import compare_version` and `_RICH_AVAILABLE: bool = _package_available("rich") and compare_version("rich", operator.ge, "10.2.2")` You can refer to the similar issue as well. [Lightning-AI/torchmetrics#1923](https://github.com/Lightning-AI/torchmetrics/issues/1923)

Thank you very much for sharing this!

**Comment by fangxy100** [comment]
pip install torchmetrics==0.7.0

**Comment by ZXXaaaa** [comment]
I have met the same problem , and i solve it by changing the version of pytorch_lightning to 1.8.6
